import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet-routing-machine/dist/leaflet-routing-machine.css";
import Navbar from "@/components/Navbar";
import "leaflet/dist/leaflet.css";
import StateProvider from "@/store/StateProvider";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <NextTopLoader
          color="#16a34a"
          showSpinner={true}
          height={4}
          zIndex={99999}
        />
        <StateProvider>
          <MainRoot>{children}</MainRoot>
        </StateProvider>
      </body>
    </html>
  );
}

const MainRoot = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Navbar />
      <div className="flex-1 h-full [&>*]:pt-14">{children}</div>
    </>
  );
};
